
# Auth API
POST  http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "displayName": "Miki Schumacher",
    "password": "123456",
    "username": "mischumacher",
    "emailAddress": "mischumacher@f1.com"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "password": "123456",
    "username": "mischumacher"
}

###

GET  http://localhost:3000/api/auth/logout HTTP/1.1
Content-Type: application/json

###

# Movies API

GET http://localhost:3000/api/movies/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I


###

GET http://localhost:3000/api/surveys/list HTTP/1.1
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I

###


GET http://localhost:3000/api/survey-results/list HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I

###


GET http://localhost:3000/api/survey-results/list/2023 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I

###

POST http://localhost:3000/api/surveys/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I

{
    "name": "Toy Story 3",
    "surveyId": "2020",
    "json": {}
}

###

POST http://localhost:3000/api/survey-results/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODIxMjk4OTEsImV4cCI6MTY4MjczNDY5MX0.l5_UqmFGVvphNIOjSFQGCQ8vfVtHbnfyD-sGVPn073I

{
    "surveyId": "2023",
    "json": [{
        "satisfaction-score": 5,
        "nps-score": 10
        }, {
        "satisfaction-score": 5,
        "nps-score": 9
        }, {
        "satisfaction-score": 3,
        "nps-score": 6
        }, {
        "satisfaction-score": 3,
        "nps-score": 6
        }, {
        "satisfaction-score": 2,
        "nps-score": 3
    }]
}

###

GET http://localhost:3000/api/surveys/643f5001a5b6ff010a697361 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODE0MzYwMzgsImV4cCI6MTY4MjA0MDgzOH0.FMOXSUF1LSU9vFjkLUWQuyuUUB1bJebBNCvca84hu7o

###

GET http://localhost:3000/api/surveys/edit/643f501fa5b6ff010a697366 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODE0MzYwMzgsImV4cCI6MTY4MjA0MDgzOH0.FMOXSUF1LSU9vFjkLUWQuyuUUB1bJebBNCvca84hu7o

{
      "name": "Test Survey Altered",
      "surveyId": "1",
      "json": {}
}

###

GET http://localhost:3000/api/movies/63e93f0f2931f790dac55deb HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODE0MzYwMzgsImV4cCI6MTY4MjA0MDgzOH0.FMOXSUF1LSU9vFjkLUWQuyuUUB1bJebBNCvca84hu7o


###
POST http://localhost:3000/api/movies/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODE0MzYwMzgsImV4cCI6MTY4MjA0MDgzOH0.FMOXSUF1LSU9vFjkLUWQuyuUUB1bJebBNCvca84hu7o

{
    "name": "Toy Story 3",
    "year": "2020",
    "director": "Mr. Nobody",
    "genre": "Animated",
    "runtime": 500
}


###
PUT http://localhost:3000/api/movies/edit/63f98e8b7f00f4865870e6d3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2ODE0MzYwMzgsImV4cCI6MTY4MjA0MDgzOH0.FMOXSUF1LSU9vFjkLUWQuyuUUB1bJebBNCvca84hu7o

{
    "name": "Toy Story 2",
    "year": "2020",
    "director": "Mr. Nobody",
    "genre": "Animated",
    "runtime": 120
}

###
DELETE http://localhost:3000/api/movies/delete/63f98e8b7f00f4865870e6d3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjk4YzJjNmFiODJkZWQ2MDA2NzU5NCIsImRpc3BsYXlOYW1lIjoiTWlraSBTY2h1bWFjaGVyIiwidXNlcm5hbWUiOiJtaXNjaHVtYWNoZXIiLCJpYXQiOjE2NzczMDA1ODAsImV4cCI6MTY3NzkwNTM4MH0.pSuq_gpQdvpDLa3KvdFQDxF2mdGpyzm9TshK99YMLKE